services:
  - type: web
    name: react-chess
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build -p $PORT
    envVars:
      - key: NODE_VERSION
        value: 20.x